---
- name: add nodejs repo
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add nodejs repository
  shell: >
      echo "deb https://deb.nodesource.com/node trusty main\n
      deb-src https://deb.nodesource.com/node trusty main" >
      /etc/apt/sources.list.d/nodesource.list

- name: install nodejs
  apt: name=nodejs state=present update_cache=yes
